name: Axescode-Front
version: '1.0'
main: com.github.axessystem.AxesFront
api-version: 1.19
libraries:
  - io.github.monun:kommand-core:3.1.6
  - io.github.monun:tap-core:4.9.6
  - io.github.monun:heartbeat-coroutines:0.0.5
depend:
  - Axescode-Core

